### ISSUE TITLE
 Cannot find module 'istanbul-cobertura-badger' 

### ISSUE THREAD

**Issue by BossaGroove** [intuit/istanbul-cobertura-badger#12]
The path inside `package.json` goes wrong:

```
...
"main": "./index.js",
...
```

should be 

```
...
"main": "./lib/index.js",
...
```

**Comment by destroyerofbuilds** [comment]
I've just encountered this issue myself now that my build is taking up v1. In the meantime I'll be downgrading to resolve my local issue.

**Comment by hbetts** [comment]
@BossaGroove I've filed #13 to resolve this issue.

**Comment by marcellodesales** [comment]
@BossaGroove and @hbetts  thanks for verifying this... I will disable the tests that are failing. I was testing them in our local jenkins :(

**Comment by marcellodesales** [comment]
Just released the new version:

* https://github.com/intuit/istanbul-cobertura-badger/releases/tag/1.0.1

```
$ npm publish
+ istanbul-cobertura-badger@1.0.1
```

Let me know if that's working...
