### ISSUE TITLE
Threshold are always NaN

### ISSUE THREAD

**Issue by edravis** [intuit/istanbul-cobertura-badger#17]
No matter how I run the script I always get this:
```
 overallPercent: NaN,
  functionRate: NaN,
  lineRate: 0.8214,
  branchRate: 0.5,
  url: 'http://img.shields.io/badge/coverage-NaN%-red.svg',
  badgeFile:
   { downloaded: true,
     filePath: 'mypath/coverage.svg',
     size: 742 },
  color: 'red' }
Badge created at mypath/coverage.svg
```

I've tried:
`istanbul-cobertura-badger -f -v` *global*
`node_modules/.bin/istanbul-cobertura-badger -f -v` *local*
`istanbul-cobertura-badger -e 80 -g 60 -v`
`istanbul-cobertura-badger -f -r mypath/cobertura.xml -v`

I've checked also the cobertura.xml and looks fine.

Any idea?

**Comment by marcellodesales** [comment]
@edravis Let me take a look this week and get back to you! Sorry about that...

**Comment by marcellodesales** [comment]
@edravis I just found out that the API was getting a 301... It looks like that shilds.io changed their URLs to be protected... Changed the URL to include https and worked with the local test.

```sh
 $ ./lib/cli.js -f -v local
{ overallPercent: 88,
  functionRate: 0.9523809523809523,
  lineRate: 0.9231,
  branchRate: 0.7973,
  url: 'https://img.shields.io/badge/coverage-88%-yellow.svg',
  badgeFile: 
   { downloaded: true,
     filePath: '/home/mdesales/dev/github/intuit/istanbul-cobertura-badger/coverage/coverage.svg',
     size: 733 },
  color: 'yellow' }
Badge created at /home/mdesales/dev/github/intuit/istanbul-cobertura-badger/coverage/coverage.svg
```

I'm replacing the http library and it should all be fixed.

**Comment by marcellodesales** [comment]
@edravis I just found out that the API was getting a 301... It looks like that shilds.io changed their URLs to be protected... Changed the URL to include https and worked with the local test.

```sh
 $ ./lib/cli.js -f -v local
{ overallPercent: 88,
  functionRate: 0.9523809523809523,
  lineRate: 0.9231,
  branchRate: 0.7973,
  url: 'https://img.shields.io/badge/coverage-88%-yellow.svg',
  badgeFile: 
   { downloaded: true,
     filePath: '/home/mdesales/dev/github/intuit/istanbul-cobertura-badger/coverage/coverage.svg',
     size: 733 },
  color: 'yellow' }
Badge created at /home/mdesales/dev/github/intuit/istanbul-cobertura-badger/coverage/coverage.svg
```

I'm replacing the http library and it should all be fixed.

**Comment by marcellodesales** [comment]
@edravis Please reopen this if you find a related error again!

**Comment by edravis** [comment]
@marcellodesales working as expected! cool job

**Comment by marcellodesales** [comment]
Thanks @edravis!!! This has been helping me a lot!!!
