### ISSUE TITLE
100% Unachiveable

### ISSUE THREAD

**Issue by destroyerofbuilds** [intuit/istanbul-cobertura-badger#19]
Seems the percentage math is setup so that 100% can't be achieved.

In my particular case, I have a `functionRate` of 1, a `lineRate` of 1, and a `branchRate` of 1. However, the coverage percentage comes out to `99%`.

```javascript
var percent = (((functionRate + lineRate + branchRate) / 3) * 100).toFixed(0) - 1;
```

**Comment by marcellodesales** [comment]
Humm @destroyerofbuilds ... Let me guess... Do you see this `-1` in the formula??? :D I'm sure I messed it up some day change the "toFixed(0)" from other functions...

**Comment by marcellodesales** [comment]
Will be sending the fix to this https://github.com/intuit/istanbul-cobertura-badger/commit/e76a6e38a728987e7a6723209c9ccc262d950408#commitcomment-15004608

**Comment by marcellodesales** [comment]
@destroyerofbuilds Please verify the new version 1.2.1!!! I added the test case for the problem as well!!!

**Comment by destroyerofbuilds** [comment]
@marcellodesales I can confirm the latest code is behaving as desired.

Thank you for all the hard work!

**Comment by marcellodesales** [comment]
@destroyerofbuilds Awesome!!! I'm glad it is working properly now! :+1: Thank you for the verifications!
